// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = 'https://saolquzcckfjvntgrzuq.supabase.co';
const SUPABASE_PUBLISHABLE_KEY =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNhb2xxdXpjY2tmanZudGdyenVxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwMzYxNTIsImV4cCI6MjA2MjYxMjE1Mn0.98NMQYfU64xkZURtOXAjkP5j-e5b0eSIN_yzaIc2_GU';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY
);
