// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://podwnipoalxmikaoadvc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBvZHduaXBvYWx4bWlrYW9hZHZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5NDM2OTYsImV4cCI6MjA2MjUxOTY5Nn0.B_VYxBbFaS07TuuKnfWfPtni_yN1D5KSddNhd_CrdfY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);